version: 2.1
orbs:
  node: circleci/node@1.1
  npm-publisher: uraway/npm-publisher@0.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: "14.15"
    steps:
      - checkout
      - run: npm test
workflows:
  test_and_npm_publish_and_git_tag_push:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - npm-publisher/publish-from-package-version:
          requires:
            - test
          filters:
            branches:
              only: main
          ssh-fingerprints: b9:c4:aa:e9:10:4a:16:ca:ef:19:dd:b8:2e:00:4e:fa
          publish-token-variable: NPM_TOKEN
          push-git-tag: true